# Generated by Django 4.1.3 on 2022-11-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=10)),
                ('profesión', models.CharField(max_length=15)),
                ('areaOrientar', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=10)),
            ],
        ),
    ]
